// eliminate ide undefined errors
let g;
let Bangle;

// fonts
const font815_large = atob("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/8PAP/8PAP/8PAP/8PAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP4AAAP8AAAP8AAAP4AAAAAAAAAAAAAP4AAAP8AAAP8AAAP4AAAAAAAAAAAAAAAAAAAAAAAAMDAAAMDAAP///AP///AP///AP///AAMDAAAMDAAP///AP///AP///AP///AAMDAAAMDAAAAAAAAAAAAAAAAAAAAAAA8AQAB+A4AD/A8AD/gcA/nwPw/D4Pw/B8Pw/A+fwDgf8ADwP8ABwH4AAgDwAAAAAAAAAAAB4ADgD8APwD8A/wB4D/wAAP/AAA/8AAD/wAAP/AAA/8AAD/wAAP/AeAP8A/APwA/AHAAeAAAAAAAAAAAAAP8AAAf+ADw//AH4//AP/wDAP/wDAMP4DAMP8DAP8/+AP8f+AH4P/ADwP/AAA+DAAA8DAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAHAAAGPAAAPfAAAP+AAAP8AAAP4AAAHwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//wAD//8AP///Af///g/wA/w+AAHw4AABwQAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAg4AABw+AAHw/wA/wf///gP///AD//8AA//wAAAAAAAAAAAAAAAAAAAAAAAwAAAAwAAAYxgAA97wAA//wAAf/gAAD8AAAD8AAAD8AAAD8AAAf/gAA//wAA97wAAYxgAAAwAAAAwAAAAAAAAAAAAAAwAAAAwAAAAwAAAAwAAAf/gAA//wAA//wAAf/gAAAwAAAAwAAAAwAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAcAAAQ8AAA48AAA/4AAA/wAAA/gAAAfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAwAAAAwAAAAwAAAAwAAAAwAAAAwAAAAwAAAAwAAAAwAAAAwAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeAAAA/AAAA/AAAAeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAD8AAAP8AAA/8AAD/wAAP/AAA/8AAD/wAAP/AAA/8AAD/wAAP/AAA/8AAA/wAAA/AAAAcAAAAA//wAD//8AH//+AH//+AOAOHAMAcDAMA4DAMBwDAMDgDAOHAHAH//+AH//+AD//8AA//wAAAAAAAAAAAAAAAAAAAAAAQADAAwADABwADADwAHAH///AP///AP///AP///AAAAHAAAADAAAADAAAADAAAAAAAAAAAAAAAAAAAAADgA+AHwB/APwD/APgH/AOAPjAMAfDAMA+DAOB8DAP/4DAP/wDAH/gDAD/ADAAAAAAAAAAAAAAAAAAAAADgAcAHwA+APwA/APgAfAMAwDAMAwDAMAwDAMAwDAP///AP///AH/P+AD+H8AAAAAAAAAAAAB4AAAD8AAAH8AAAP8AAAeMAAA8MAAB4MAADwMAAH//+AP///AP///AH//+AAAMAAAAMAAAAAAAAAAAAAAAAAAAAAAH+AcAP/A+AP/A/AP/AfAMDAHAMDADAMDADAMDAHAMD//AMD//AMB/+AMA/8AAAAAAAAAAAAAAAAAAAAAA//8AB//+AD///AH///APDADAODADAMDADAMDADAMD//AMD//AAB/+AAA/8AAAAAAAAAAAAAAAAAAAAAMAAAAMAAAAMAAAAMAAAAMAP+AMA//AMD//AMP/+AP/8AAP/wAAP/AAAH8AAAAAAAAAAAAAAAAAAAAAAAD+H8AH/P+AP///AP///AMDwDAMDwDAMA8DAMA8DAP///AP///AH/P+AD+H8AAAAAAAAAAAAAAAAAAAAAD/AAAH/gAAP/wDAP/wDAMAwDAMAwDAMAwHAMAwPAP//+AP//8AH//4AD//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4AeAD8A/AD8A/AB4AeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAcAAAQ8AAA58B4A/4D8A/wD8A/gB4AfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAB4AAAD8AAAH+AAAP/AAAfPgAA+HwAB8D4AD4B8ADwA8ADgAcABAAIAAAAAAAAAAAAAAAAAAAAAAMDAAAMDAAAMDAAAMDAAAMDAAAMDAAAMDAAAMDAAAMDAAAMDAAAMDAAAMDAAAAAAAAAAAAAAAAAAAAAABAAIADgAcADwA8AD4B8AB8D4AA+HwAAfPgAAP/AAAH+AAAD8AAAB4AAAAwAAAAAAAAAAAAAAAAAAAAAAOAAAAfAAAA/AAAA+AAAA4D4GAwH8PAwP8PA4f4GA/+AAA/8AAAf4AAAPwAAAAAAAAAAAAAD//8AH//+AP///AP///AMAADAMAADAMB+DAMD/DAMD/DAMD/DAP//DAP//DAH/+AAD/8AAAAAAAAAAAAAAAAAAAAAAA//+AB///AD///AH//+APAwAAOAwAAOAwAAPAwAAH//+AD///AB///AA//+AAAAAAAAAAAAAAAAAAAAAH//+AP///AP///AP///AMAwDAMAwDAMD8DAOD8HAP///AP/P/AH+H+AD8D8AAAAAAAAAAAAAAAAAAAAAD//8AH//+AP///AP///AOAAHAMAADAMAADAOAAHAPgAfAPwA/AHwA+ADgAcAAAAAAAAAAAAAAAAAAAAAH//+AP///AP///AP///AOAAHAMAADAOAAHAPAAPAH//+AD//8AB//4AA//wAAAAAAAAAAAAAAAAAAAAAH//+AP///AP///AP///AOAwHAMAwDAMAwDAMAwDAMAwDAMAwDAMAADAMAADAAAAAAAAAAAAAAAAAAAAAH//+AP///AP///AP//+AODAAAMDAAAMDAAAMDAAAMDAAAMDAAAMAAAAMAAAAAAAAAAAAAAAAAAAAAAAAD//8AH//+AP///AP///AOAAHAMAADAMAwDAMAwHAPg//APw//AHw//ADgf+AAAAAAAAAAAAAAAAAAAAAH//+AP///AP///AH//+AAB4AAAAwAAAAwAAAB4AAH//+AP///AP///AH//+AAAAAAAAAAAAAAAAAAAAAMAADAMAADAMAADAOAAHAP///AP///AP///AP///AOAAHAMAADAMAADAMAADAAAAAAAAAAAAAAAAAAAAAAAAcAAAA+AAAA/AAAAfAAAAHAAAADAAAADAAAAHAH///AP///AP//+AH//8AAAAAAAAAAAH//+AP///AP///AH//+AAAwAAAB4AAAD8AAAP+AAA/PwAD+H8AH8D+AP4B/APgAfAGAAGAAAAAAAAAAAAAAAAAAAAAH//+AP///AP///AH///AAAAHAAAADAAAADAAAADAAAADAAAADAAAADAAAADAAAAAAAAAAAH//+AP///AP///AH//+AD8AAAA/AAAAPwAAAPwAAA/AAAD8AAAH//+AP///AP///AH//+AAAAAAAAAAAH//+AP///AP///AH//+AA/gAAAPwAAAH4AAAB+AAAA/AAAAfwAH//+AP///AP///AH//+AAAAAAAAAAAAAAAAAAAAAB//4AH//+AH//+AP///AOAAHAMAADAMAADAOAAHAP///AH//+AH//+AB//4AAAAAAAAAAAAAAAAAAAAAH//+AP///AP///AP//+AOAwAAMAwAAMAwAAMBwAAP/wAAP/wAAH/gAAD/AAAAAAAAAAAAAAAAAAAAAAAD//8AH//+AP///AP///AMAAHAMAADgMAADwMAAHwP///4P///cH//+MD//8AAAAAAAAAAAAAAAAAAAAAH//+AP///AP///AP//+AOAwAAMAwAAMA4AAOB8AAP//+AP///AH/H/AD+D+AAAAAAAAAAAAAAAAAAAAAD8AcAH+A+AP/A/AP/gfAMPwHAMD4DAMB8DAMA/DAPgf/APwP/AHwH+ADgD8AAAAAAAAAAAAAAAAAAAAAMAAAAMAAAAMAAAAMAAAAP//+AP///AP///AP//+AMAAAAMAAAAMAAAAMAAAAAAAAAAAAAAAAAAAAAAAAH//8AP//+AP///AH///AAAAHAAAADAAAADAAAAHAH///AP///AP//+AH//8AAAAAAAAAAAAAAAAAAAAAH/8AAP//AAP//wAH//8AAAD+AAAAfAAAAfAAAD+AH//8AP//wAP//AAH/8AAAAAAAAAAAAH//+AP///AP///AH//+AAAD8AAAPwAAA/AAAA/AAAAPwAAAD8AH//+AP///AP///AH//+AAAAAAAAAAAHAAOAPgAfAPwA/AH4B+AB8D4AA/PwAAf/gAAP/AAAP/AAAf/gAA/PwAB8D4AH4B+APwA/APgAfAHAAOAHAAAAPwAAAP8AAAH/AAAB/wAAAf8AAAH/+AAD//AAD//AAH/+AAf8AAB/wAAH/AAAP8AAAPwAAAHAAAAAAAAAAAAAAMAAOAMAA/AMAD/AMAP/AMA/vAMD/DAMP8DAOfwDAP/ADAP8ADAPwADAHAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf///g////w////w////wwAAAwwAAAwwAAAwwAAAwAAAAAAAAAAAAAAAAAAAA8AAAA/AAAA/wAAA/8AAAP/AAAD/wAAA/8AAAP/AAAD/wAAA/8AAAP/AAAD/wAAA/8AAAP8AAAD8AAAA8AAAAAAAAAAAAAAAAAAAAwAAAwwAAAwwAAAwwAAAw////w////w////wf///gAAAAAAAAAAAAAAAAAAAAAGAAAAPAAAA/AAAD+AAAP4AAAfgAAA8AAAA8AAAAfgAAAP4AAAD+AAAA/AAAAPAAAAGAAAAAAAAAAAAAAAADAAAADAAAADAAAADAAAADAAAADAAAADAAAADAAAADAAAADAAAADAAAADAAAADAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAA4AAAA8AAAAeAAAAPAAAAHgAAADwAAABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8AAAH+AADP/AADP/AADOHAADMDAADMDAADMDAAD//AAD//AAB//AAA/+AAAAAAAAAAAAAAAAAAAAAH//+AP///AP///AH///AADADAADADAADADAADgHAAD//AAD//AAB/+AAA/8AAAAAAAAAAAAAAAAAAAAAAA/8AAB/+AAD//AAD//AADgHAADADAADADAADADAADgHAADwPAABwOAAAgEAAAAAAAAAAAAAAAAAAAAAAA/8AAB/+AAD//AAD//AADgHAADADAADADAADADAH///AP///AP///AH//+AAAAAAAAAAAAAAAAAAAAAAA/8AAB/+AAD//AAD//AADDDAADDDAADDDAADDDAAD/DAAD/DAAB/AAAA+AAAAAAAAAAAAAAAAAAAAAAADAAAADAAAD//+AH///AP///AP//+AODAAAMDAAAMDAAAMDAAAMDAAAMDAAAAAAAAAAAAAAAAAAAAAAAAA/8DAB/+DAD//DAD//DADgHDADADDADADDADADHAD///AD///AD//+AB//8AAAAAAAAAAAAAAAAAAAAH//+AP///AP///AH//+AADgAAADAAAADAAAADgAAAD/+AAD//AAB//AAA/+AAAAAAAAAAAAAAAAAAAAAADAAAADAAAADAAAADAAAGD/+APD//APD//AGB//AAAADAAAADAAAADAAAADAAAAAAAAAAAAAAAAAAAAAAAAADAAAADAAAADAAAADAAAADAAAADGB///PD///PD//+GB//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH//+AP///AP///AH//+AAADAAAAHgAAAPwAAAf4AAB8+AAD4fAADwPAABgGAAAAAAAAAAAAAAAAAAAAAMAAAAMAAAAMAAAAMAAAAP//+AP///AP///AH///AAAADAAAADAAAADAAAADAAAAAAAAAAAAB/+AAD//AAD//AAD/+AABwAAAAwAAAA/8AAA/8AABwAAADwAAAD/+AAD//AAB//AAA/+AAAAAAAAAAAAAAAAAAAAAAB/+AAD//AAD//AAD/+AADgAAADAAAADAAAADgAAAD/+AAD//AAB//AAA/+AAAAAAAAAAAAAAAAAAAAAAA/8AAB/+AAD//AAD//AADgHAADADAADADAADgHAAD//AAD//AAB/+AAA/8AAAAAAAAAAAAAAAAAAAAAAB//+AD///AD///AD//+ADADAADADAADADAADgHAAD//AAD//AAB/+AAA/8AAAAAAAAAAAAAAAAAAAAAAA/8AAB/+AAD//AAD//AADADAADADAADADAADADAAD//+AD///AD///AB//+AAAAAAAAAAAAAAAAAAAAAB/+AAD//AAD//AAD/+AADAAAADAAAADAAAADAAAAD4AAAD8AAAB8AAAA4AAAAAAAAAAAAAAAAAAAAAAAA8DAAB+DAAD/DAAD/DAADnDAADDDAADDDAADDnAADD/AADD/AADB+AADA8AAAAAAAAAAAAAAAAAAAAAADAAAADAAAB//8AD//+AD///AB///AADAHAADADAADADAADADAADADAADADAAAAAAAAAAAAAAAAAAAAAAB/8AAD/+AAD//AAB//AAAAHAAAADAAAADAAAAHAAB//AAD//AAD//AAB/+AAAAAAAAAAAAAAAAAAAAAAB/wAAD/4AAD/8AAB/+AAAAPAAAAHAAAAHAAAAPAAB/+AAD/8AAD/4AAB/wAAAAAAAAAAAAB/wAAD/4AAD/+AAB//AAAAPAAAAeAAAP8AAAP8AAAAeAAAAPAAB//AAD/+AAD/4AAB/wAAAAAAAAAAAABgGAADwPAAD4fAAB8+AAAf4AAAPwAAAHgAAAHgAAAPwAAAf4AAB8+AAD4fAADwPAABgGAAAAAAAAAAAAAAAAAAAAAAB/8DAD/+DAD//DAB//DAAAHDAAADDAAADDAAADHAB///AD///AD//+AB//8AAAAAAAAAAAAAAAAAAAAADAGAADAPAADAfAADA/AADB7AADDzAADHjAADPDAAD+DAAD8DAAD4DAABwDAAAAAAAAAAAAAwAAAAwAAAAwAAAAwAAAAwAAAB4AAP///Af///g//P/w/+H/w4AABwwAAAwwAAAwwAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////8////8////8////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAwwAAAwwAAAw4AABw//P/w//P/wf///gP///AAB4AAAAwAAAAwAAAAwAAAAwAAAAwAAAAAAAAAAAAAA8AAAB8AAADwAAADgAAADAAAADgAAAD4AAAB8AAAAcAAAAMAAAAcAAAA8AAAD4AAADwAAAAAAAAAAAA");
const font815_xlarge = atob("AD/////AAAAP/////wAAAf/////4AAA//////8AAB//////+AAB//////+AAD///////AAD///////AAD/AAB8D/AAD8AAD4A/AAD4AAHwAfAAD4AAPgAfAADwAAfAAPAADwAA+AAPAADwAB8AAPAADwAD4AAPAAD4AHwAAfAAD4APgAAfAAD8AfAAA/AAD/A+AAD/AAD///////AAD///////AAB//////+AAB//////+AAA//////8AAAf/////4AAAP/////wAAAD/////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AAAAPAAAA8AAAAPAAAA8AAAAPAAAA8AAAAPAAAB8AAAAPAAAB8AAAAfAAAD8AAAAfAAAD8AAAB/AAAH//////AAAP//////AAA///////AAD///////AAD///////AAD///////AAD///////AAD///////AAAAAAAAB/AAAAAAAAAfAAAAAAAAAfAAAAAAAAAPAAAAAAAAAPAAAAAAAAAPAAAAAAAAAPAAAAAAAAAPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAP/AAA/8AAA//AAB/8AAB//AAB/8AAD//AAD/8AAH//AAD/8AAP//AAD/8AAf//AAD/8AA///AADwAAB/4PAADwAAD/gPAADwAAH/APAADwAAP+APAADwAAf8APAADwAA/4APAADwAB/wAPAADwAH/gAPAAD////AAPAAD///+AAPAAD///8AAPAAD///4AAPAAB///wAAPAAB///gAAPAAA///AAAPAAAP/8AAAPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAA/wAAA/8AAA/8AAB/8AAA/+AAB/8AAA/+AAD/8AAA//AAD/8AAA//AAD/8AAA//AAD/8AAA//AADwAA8AAPAADwAA8AAPAADwAA8AAPAADwAA8AAPAADwAA8AAPAADwAA8AAPAADwAA8AAPAADwAA8AAPAAD///////AAD///////AAD///n///AAD///n///AAB///D//+AAB///D//+AAA//+B//8AAAP/4Af/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/wAAAAAAAP/wAAAAAAAf/wAAAAAAA//wAAAAAAB//wAAAAAAD//wAAAAAAH//wAAAAAAP//wAAAAAAf8DwAAAAAA/4DwAAAAAB/wDwAAAAAD/gDwAAAAAH/ADwAAAAAP+ADwAAAAAf8ADwAAAAA/4ADwAAAAB///////AAD///////AAD///////AAD///////AAD///////AAD///////AAD///////AAD///////AAAAAADwAAAAAAAADwAAAAAAAADwAAAAAAAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///AA/wAAD///AA/8AAD///AA/+AAD///AA/+AAD///AA//AAD///AA//AAD///AA//AAD///AA//AADwAPAAAPAADwAPAAAPAADwAPAAAPAADwAPAAAPAADwAPAAAPAADwAPAAAPAADwAPAAAPAADwAPAAAPAADwAP////AADwAP////AADwAP////AADwAP////AADwAH///+AADwAH///+AADwAD///8AADwAA///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////wAAAP/////8AAAf/////+AAA//////+AAB///////AAB///////AAD///////AAD///////AAD/APAAAPAAD8APAAAPAAD4APAAAPAAD4APAAAPAADwAPAAAPAADwAPAAAPAADwAPAAAPAADwAPAAAPAADwAP////AADwAP////AADwAP////AADwAP////AAAAAH///+AAAAAH///+AAAAAD///8AAAAAA///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwAAAAAAAADwAAAAAAAADwAAAAAAAADwAAAAAAAADwAAAAAAAADwAAAAAAAADwAAAAAAAADwAAAAAAAADwAAAD//AADwAAAP//AADwAAA///AADwAAD///AADwAAP///AADwAA////AADwAD////AADwAP////AAD////8AAAAD////wAAAAD////AAAAAD///8AAAAAD///wAAAAAD///AAAAAAD//8AAAAAAD//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/4Af/wAAA//+B//8AAB//+B//+AAB///D//+AAD///////AAD///////AAD///////AAD///////AADwAfwAAPAADwAP4AAPAADwAH8AAPAADwAD+AAPAADwAB/AAPAADwAA/gAPAADwAAfwAPAADwAAP4APAAD///////AAD///////AAD///////AAD///////AAB///D//+AAB//+B//+AAA//+B//8AAAP/4Af/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//8AAAAAA////AAAAAB////gAAAAB////gAAAAD////wAPAAD////wAPAAD////wAPAAD////wAPAADwAADwAPAADwAADwAPAADwAADwAPAADwAADwAPAADwAADwAfAADwAADwAfAADwAADwA/AADwAADwD/AAD///////AAD///////AAD//////+AAD//////+AAB//////8AAB//////4AAA//////wAAAP/////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB+AAAH4AAAH/gAAf+AAAP/wAA//AAAP/wAA//AAAP/wAA//AAAP/wAA//AAAH/gAAf+AAAB+AAAH4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
Graphics.prototype.setFont8x15Large = function() {
  this.setFontCustom(font815_large, 32, 16, 30);
};
Graphics.prototype.setFont8x15Huge = function() {
  this.setFontCustom(font815_xlarge, 48, 32, 60);
};

let init = true;
const pos = {
  hrmin:{ x:  24, y:  30 },
  sec:  { x: 190, y:  54 },
  date: { x:  10, y:  90 },
  ts:   { x:  40, y: 120 },
  doy:  { x:  40, y: 150 },
  pcy:  { x:  40, y: 180 },
  et:   { x:  56, y: 210 }
};
const col = {
  hrmin:( 0 << 11) | (55 << 5),
  sec:  ( 0 << 11) | (47 << 5) | (31 << 0),
  date: (31 << 11) | (55 << 5),
  et:   (31 << 11) | (31 << 5),
  ts:   ( 0 << 11) | (31 << 5) | (31 << 0),
  doy:  (31 << 11) | ( 0 << 5) | (31 << 0),
  pcy:  (31 << 11) | (15 << 5) | (0 << 0)
};
const months = ["Jan","Feb","Mar","Apr","Mai","Jun","Jul","Aug","Sep","Okt","Nov","Dez"];
const dpm = (m,y) => (m==2&&ly(y))?29:[31,28,31,30,31,30,31,31,30,31,30,31][m];
const weekdays = ["So","Mo","Di","Mi","Do","Fr","Sa"];
const ly = (y) => !!((!(y%4) && y%100) ||(!(y%400)));
const spy = (y) => (ly(y)?366:365)*24*60*60;
const spm = (m,y) => dpm(m,y)*24*60*60;
const doy = (d,m,y) => [0,31,59,90,120,151,181,212,243,273,304,334][m]+d+((m>2 && ly(y))?1:0);
const onMinute = (now) => {
  // time
  let h = now.getHours();
  let m = now.getMinutes();
  g.setFont8x15Huge();
  g.setColor(col.hrmin);
  g.drawString((h<10?"0":"")+h+":"+(m<10?"0":"")+m, pos.hrmin.x, pos.hrmin.y, true);
  // date
  g.setFont8x15Large();
  g.setColor(col.date);
  g.drawString(weekdays[now.getDay()]+" "+(now.getDate() < 10?" ":"")+now.getDate()+"."+months[now.getMonth()]+"."+now.getFullYear(), pos.date.x, pos.date.y, true);
};

const onSecond = () => {
  let now = new Date();
  if(init || now.getSeconds() == 0) {
    onMinute(now);
    init = false;
  }
  // seconds
  g.setFont8x15Large();
  let s = now.getSeconds();
  g.setColor(col.sec);
  g.drawString((s<10?"0":"")+s, pos.sec.x, pos.sec.y, true);
  // ET
  let et = now.getTime() * 20.571428571428573;
  let em = parseInt((et/60e3)%60);
  let eh = parseInt((et/3600e3)%24);
  let ex = "ET "+(eh<10?"0":"")+eh+":"+(em<10?"0":"")+em;
  g.setColor(col.et);
  g.drawString(ex, pos.et.x, pos.et.y, true);
  // TS
  g.setColor(col.ts);
  g.drawString(Math.floor(now.getTime()/1000),pos.ts.x, pos.ts.y, true);
  // percentages
  let dy = now.getDate(), mo = now.getMonth(), yr = now.getFullYear();
  let ndoy = doy(dy,mo,yr);
  let pcd = (now.getHours()*3600 + now.getMinutes()*60+now.getSeconds())/(24*3600);
  g.setColor(col.doy);
  g.drawString("D "+(ndoy<100?ndoy<10?"  ":" ":"")+(ndoy+pcd).toFixed(4).replace("."," "),pos.doy.x, pos.doy.y, true);
  let pcy = (pcd+ndoy-1)/(ly(yr)?366:365);
  g.setColor(col.pcy);
  g.drawString("Y  "+pcy.toFixed(7).slice(2), pos.pcy.x, pos.pcy.y, true);
};

const startTimers = () => {
  timer = setInterval(onSecond, 1000);
};

Bangle.on('lcdPower', (on) => {
  if (on) {
    // g.clear();
    init = true;
    startTimers();
    onSecond();
    Bangle.drawWidgets();
  } else {
    if (timer) {
      clearInterval(timer);
    }
  }
});

g.clear();
startTimers();
onSecond();
Bangle.loadWidgets();
Bangle.drawWidgets();

// Show launcher when middle button pressed
setWatch(Bangle.showLauncher, BTN2, { repeat: false, edge: "falling" });